# Generated by Django 5.1.7 on 2025-03-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
